kind: pipeline
type: docker
name: default

steps:
- name: waiton 
  image: akhenakh/drone-waiton:1.0
  pull: always
  settings:
    globaltimeout: 30s 
    urls:
    - tcp://cache:6379

- name: service-ready
  image: busybox
  commands:
  - echo "redis ready"
  depends_on:
  - waiton

services:
- name: cache
  image: redis
  ports:
  - 6379 
