kind: pipeline
type: kubernetes
name: default

steps:
- name: waiton 
  image: akhenakh/drone-waiton:1.0
  pull: always
  settings:
    globaltimeout: 30s 
    urls:
    - tcp://cache:6379

- name: service-ready
  image: busybox
  commands:
  - echo "redis ready"
  depends_on:
  - waiton

- name: build_image
  image: akhenakh/drone-kaniko
  pull: always
  settings:
    registry: registry.lan.inair.space:5000
    repo: drone-waiton
    insecure: true
    verbose: true

services:
- name: cache
  image: redis
  ports:
  - 6379 
