kind: pipeline
type: docker
name: default

steps:
- name: waiton 
  image: akhenakh/drone-waiton:1.0
  settings:
    globaltimeout: 3s
    urls: 
    - http://www.google.com
    - http://httpbin.org/delay/5
