kind: pipeline
type: docker
name: default

steps:
- name: waiton 
  image: akhenakh/drone-waiton:1.0
  pull: always
  settings:
    globaltimeout: 30s 
    urls:
    - tcp://cache:6379

- name: service-ready
  image: busybox
  commands:
  - echo "redis ready"
  depends_on:
  - waiton

- name: build_image
  image: akhenakh/drone-kaniko
  settings:
    repo: akhenakh/drone-waiton
    dry_run: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

services:
- name: cache
  image: redis
  ports:
  - 6379 
